/* Automatically generated by wasm2c */
#ifndef WASM_H_GENERATED_
#define WASM_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_wasi__snapshot__preview1;

typedef struct w2c_Wasm {
  struct w2c_wasi__snapshot__preview1* w2c_wasi__snapshot__preview1_instance;
  u32 w2c_g0;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_0x5F_indirect_function_table;
} w2c_Wasm;

void wasm2c_Wasm_instantiate(w2c_Wasm*, struct w2c_wasi__snapshot__preview1*);
void wasm2c_Wasm_free(w2c_Wasm*);
wasm_rt_func_type_t wasm2c_Wasm_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'wasi_snapshot_preview1' 'proc_exit' */
void w2c_wasi__snapshot__preview1_proc_exit(struct w2c_wasi__snapshot__preview1*, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_Wasm_memory(w2c_Wasm* instance);

/* export: 'encrypt' */
u32 w2c_Wasm_encrypt(w2c_Wasm*, u32, u32);

/* export: '__indirect_function_table' */
wasm_rt_funcref_table_t* w2c_Wasm_0x5F_indirect_function_table(w2c_Wasm* instance);

/* export: '_initialize' */
void w2c_Wasm_0x5Finitialize(w2c_Wasm*);

/* export: 'stackSave' */
u32 w2c_Wasm_stackSave(w2c_Wasm*);

/* export: 'stackRestore' */
void w2c_Wasm_stackRestore(w2c_Wasm*, u32);

/* export: 'stackAlloc' */
u32 w2c_Wasm_stackAlloc(w2c_Wasm*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* WASM_H_GENERATED_ */
